baseurl: https://travespielertreffen.de/
title: TraveSpielerTreffen e.V.

theme:
  - github.com/theNewDynamic/gohugo-theme-ananke

background_color_class: bg-near-black
custom_css:
  - custom.css

DefaultContentLanguage: de
languageCode: de-de
languages:
  de:
    title: TraveSpielerTreffen e.V.
    weight: 1
    contentDir: content/de
date_format: 2. January 2006

SectionPagesMenu: main
Paginate: 12
googleAnalytics: ""
enableRobotsTXT: false
recent_posts_number: 0

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params:
  site_logo: logo.png
  text_color: ""
  author: TraveSpielerTreffen e.V.
  favicon: images/favicon-32x32.png
  description: Der Brett- und Tabletop-Spielverein in der Region Hamburg und Lübeck.
  
  ananke_socials:
    - name: Facebook
      label: "facebook"
      url: https://www.facebook.com/people/TraveSpieler-Treffen-EV/pfbid0Sak1Q1tcEBt9htF4cmUJVWnFNN9BtHDmdhBRAcAfbT6T7QFd7KqfuZHGHhRgxC3wl/
    - name: Discord
      label: "discord"
      url: https://discord.gg/cSnJYsBnMz

impressum: /impressum
privacy_policy: /datenschutz
