baseURL = 'http://travespielertreffen.github.io/'
languageCode = 'de-de'
title = 'TraveSpielerTreffen e.V.'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 12
googleAnalytics = ""
enableRobotsTXT = false

[languages]
  [languages.de]
    title = "TraveSpielerTreffen e.V."
    weight = 1
    contentDir = "content/de"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  site_logo = "logo.png"
  text_color = ""
  author = "TraveSpielerTreffen e.V."
  favicon = "images/favicon-32x32.png"
  description = "Der Brett- und Tabletop-Spielverein in der Region Hamburg und Lübeck."

  disable_share = true

  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 0
  date_format = "2. January 2006"

  # Custom CSS
  custom_css = ["custom.css"]

  # Custom footer
  impressum = "/impressum"
  privacy_policy = "/datenschutz"
  discord = "https://discord.gg/cSnJYsBnMz"

  #[[params.ananke_socials]]
  #  name = "Facebook"
  #  url = "https://www.facebook.com/people/TraveSpieler-Treffen-EV/pfbid0Sak1Q1tcEBt9htF4cmUJVWnFNN9BtHDmdhBRAcAfbT6T7QFd7KqfuZHGHhRgxC3wl/"
  #  label = "Facebook"

  #[[params.ananke_socials]]
  #  name = "github"
  #  url = "https://github.com/travespielertreffen/travespielertreffen.github.io"
  #  label = "Source"

  [[params.ananke_socials]]
    name = "Discord"
    url = "https://discord.gg/cSnJYsBnMz"
    label = "Discord"
